version: 2.1
references:
  defaults: &defaults
    docker:
      - image: circleci/node:8
    working_directory: ~/today

  # Cache keys for node_modules
  npm_cache_key: &npm_cache_key
    npm-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
  npm_backup_cache_key_1: &npm_backup_cache_key_1
    npm-dependencies-{{ .Branch }}-
  npm_backup_cache_key_2: &npm_backup_cache_key_2
    npm-dependencies

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key
        - *npm_backup_cache_key_1
        - *npm_backup_cache_key_2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_node_modules
      - add_ssh_keys
      - run:
          command: |
            export PATH=$PATH:$HOME/$CIRCLE_PROJECT_REPONAME/node_modules/.bin
      - run: yarn
      - run: yarn build
      - save_cache:
          key: *npm_cache_key
          paths:
            - node_modules
      - setup_remote_docker
      - run:
          name: Build and Deploy Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t dmsi/agility-public:latest ./
            docker push dmsi/agility-public:latest

workflows:
  version: 2
  build:
    jobs:
      - build
